import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { ToasterProvider } from "./components/toaster-provider";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import React from "react";
import PropTypes from "prop-types";
import NavBar from "./components/NavBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Collaboration Platform",
  description: "Generated by create next app",
};
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ToasterProvider />
        <NavBar />
        <main className="items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
